FROM jenkins/jenkins:lts-jdk11
# Used this for below solution https://faun.pub/how-to-install-docker-in-jenkins-container-4c49ba40b373 
USER root
RUN curl https://get.docker.com/ > dockerinstall && chmod 777 dockerinstall && ./dockerinstall
